### ISSUE TITLE
Simplify usage

### ISSUE THREAD

**Issue by sect2k** [TobiasHennig/loki-nativescript-adapter#1]
I'm looking into using lokijs in my {N} app, and I came across your plugin. Like the functionality, but it seems usage could be simplified.

Instead of having to import (require) both Loki and LokiNativeScriptAdapter, you could have a small wrapper around loki what would set the appropriate adapter and then initialize loki and return it.

This:

``` js
var fs = require("file-system");
var Loki = require("./node_modules/lokijs/src/lokijs.js");
var LokiNativeScriptAdapter = require("./node_modules/loki-nativescript-adapter/loki-nativescript-adapter.js");

var path = fs.path.join(fs.knownFolders.currentApp().path, "database.db");
var db = new Loki(path, {
    adapter: new LokiNativeScriptAdapter()
});
```

becomes this:

``` js
var Loki = require("loki-nativescript-adapter");

var db = new Loki("db_name", {/*options*/});
```

As I said, the wrapper would set the adapter for loki, and also compile the path a default from "db_name" (could be overwritten with an option to the wrapper). 

Shouldn't be too much work, and if you are interested, I can put together a pull request.

Cheers,
Mitja

**Comment by TobiasHennig** [comment]
I have to think about this because the _nature_ of this repo is to provide only this single adapter. But i like the idea of a thin wrapper for Loki and this adapter to be a simple and easy to use db solution. Perhaps it's worth it to create a separate **loki-nativescript** repo to provide the wrapper and other improvements.

What are your thoughts about that?

**Comment by sect2k** [comment]
Sounds good, I've thought about taking the separate package route if you showed no interest, but given what you wrote, it actually makes more to have a separate package to begin with.

I've written a simple wrapper for my project, it's just a couple of lines, it could be a start, the code is below.

``` js
var fs = require("file-system");
var LokiJS = require("lokijs");
var NativeScriptAdapter = require("loki-nativescript-adapter");

function LokiNS(name, options) {
    options = options || {};
    var path;

    if(options.path) {
        path = options.path;
        delete options.path;
    }
    else {
        path = fs.knownFolders.currentApp().path;
    }

    options.adapter = new NativeScriptAdapter();

    return LokiJS(fs.path.join(path, name + ".db"), options);
}

 module.exports = LokiNS;
```

It's just a simple wrapper for now, but maybe some more functionality (like checking if db exists, etc ...) could be added if needed.

Let me know what you think.

**Comment by TobiasHennig** [comment]
Thank you very much for your code, i think i spend some time on [this](https://github.com/TobiasHennig/loki-nativescript).

**Comment by sect2k** [comment]
Sure, you're welcome. One thing, I would suggest naming the new package nativescript-lokijs or nativescript-loki, putting nativescript first in the name, it seems to be an unofficial convention and has the added benefit of appearing higher in npm search results than loki-nativescript.

Just my .2 cents.

**Comment by TobiasHennig** [comment]
Good advice, i've renamed it to **nativescript-loki**.
